---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    run: keycloak
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: keycloak
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:1.0
        ports:
        - containerPort: 8080